### ISSUE TITLE
Error Occurs : Adding definition to a compiled container is not allowed

### ISSUE THREAD

**Issue by wildanm** [oat-sa/generis#961]
I'm using the newest generis, and when installing tao, i encounter the following error : 

```
[2022-01-11 10:45][error]     Error Occurs : Adding definition to a compiled container is not allowed.
#0 /opt/webapps/package-tao/vendor/symfony/dependency-injection/Loader/Configurator/ServiceConfigurator.php(70): Symfony\Component\DependencyInjection\ContainerBuilder->setDefinition('Psr\\Http\\
Messag...', Object(Symfony\Component\DependencyInjection\Definition))
#1 /opt/webapps/package-tao/generis/core/DependencyInjection/ContainerServiceProvider.php(42): Symfony\Component\DependencyInjection\Loader\Configurator\ServiceConfigurator->__destruct()
#2 /opt/webapps/package-tao-data/generis/cache/services.php(6): oat\generis\model\DependencyInjection\ContainerServiceProvider->__invoke(Object(Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator))
#3 /opt/webapps/package-tao/vendor/symfony/dependency-injection/Loader/PhpFileLoader.php(149): Symfony\Component\DependencyInjection\Loader\ProtectedPhpFileLoader->{closure}(Object(Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator))
#4 /opt/webapps/package-tao/vendor/symfony/dependency-injection/Loader/PhpFileLoader.php(67): Symfony\Component\DependencyInjection\Loader\PhpFileLoader->executeCallback(Object(Closure), Object(Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator), '/Users/wildanm/...')
#5 /opt/webapps/package-tao/generis/core/DependencyInjection/ContainerBuilder.php(98): Symfony\Component\DependencyInjection\Loader\PhpFileLoader->load('services.php')
#6 /opt/webapps/package-tao/tao/install/class.Installator.php(604): oat\generis\model\DependencyInjection\ContainerBuilder->forceBuild()
#7 /opt/webapps/package-tao/tao/install/class.Installator.php(378): tao_install_Installator->recreateDependencyInjectionContainerCache()
#8 /opt/webapps/package-tao/tao/scripts/class.TaoInstall.php(134): tao_install_Installator->install(Array)
#9 /opt/webapps/package-tao/tao/scripts/class.Runner.php(114): tao_scripts_TaoInstall->run()
#10 /opt/webapps/package-tao/tao/scripts/taoInstall.php(149): tao_scripts_Runner->__construct(Array)
#11 {main}
[2022-01-11 10:45][error]     A fatal error has occurred during installation: Adding definition to a compiled container is not allowed.
```

**Comment by wildanm** [comment]
Despite the error during the installation process, but I can still login to the system.

<img width="1061" alt="Screen Shot 2022-01-11 at 17 57 14" src="https://user-images.githubusercontent.com/462398/148930402-ef4218cb-256d-4d04-9105-0f0a16ea6a7f.png">
